- name: Update web servers
  hosts: webservers
  become: true
  gather_facts: true

  tasks:
  - name: Instal·lar dependències
    ansible.builtin.apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl 
      - software-properties-common
      become: true

  - name: Instal·lar docker
    
  
