- name: Update web servers
  hosts: all
  become: true
  gather_facts: true

  tasks:
  - name: Instal·lar dependències
    ansible.builtin.apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl 
      - software-properties-common
      become: true

  - name: Afegeix la clau GPG de Docker
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      
  - name: Afegeix el repositori APT de Docker
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu stable
      state: present    
      
  - name: Update repositories cache and install apt
    ansible.builtin.apt:
      name: apt
      update_cache: yes

  - name: Instal·lar Docker
    ansible.builtin.apt:
      name: docker
      state: present
      
  - name: Afegeix la clau GPG de Kubernetes 
    ansible.builtin.apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Afegeix el repositori APT de Kubernetes
    ansible.builtin.apt_key:
      url: https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  
  - name: Instal·lar kubectl
    ansible.builtin.apt:
      name: kubectl
      state: present
  
  - name: Instal·lar Minikube
    ansible.builtin.shell:
      cmd: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      chdir: /usr/local/bin/
